import { Color, ColorLike } from './color.js';

export type RangeScaleMode = 'clamp' | 'extrema' | 'centered';
export type RangeScale = RangeScaleMode | [number, number];

function remap(
  value: number,
  oldMin: number,
  oldMax: number,
  newMin: number,
  newMax: number
): number {
  if (oldMax === oldMin) {
    return newMin;
  }
  return ((value - oldMin) / (oldMax - oldMin)) * (newMax - newMin) + newMin;
}

function computeRange(
  data: number[],
  rangeScale?: RangeScale
): [number, number] {
  if (Array.isArray(rangeScale)) {
    return rangeScale;
  }

  const mode = rangeScale ?? 'clamp';

  if (mode === 'clamp') {
    return [0, 1];
  }

  if (data.length === 0) {
    return [0, 1];
  }

  if (mode === 'extrema') {
    let min = data[0];
    let max = data[0];
    for (let i = 1; i < data.length; i++) {
      if (data[i] < min) min = data[i];
      if (data[i] > max) max = data[i];
    }
    return [min, max];
  }

  if (mode === 'centered') {
    let maxAbs = 0;
    for (let i = 0; i < data.length; i++) {
      const abs = Math.abs(data[i]);
      if (abs > maxAbs) maxAbs = abs;
    }
    return [-maxAbs, maxAbs];
  }

  throw new Error(`Unsupported range scale mode: ${String(mode)}`);
}

/**
 * Category wrapper for palette catalogs.
 */
export class ColorSchemeCategory {
  constructor(public readonly name: string) {}
}

/**
 * `ColorScheme(colors, category, notes)`
 *
 * Create a ColorScheme from an array of colors. You can also name it, assign a
 * category to it, and add notes.
 *
 * ```typescript
 * const myscheme = new ColorScheme(
 *   [Color.rgb(0.0, 0.0, 0.0), Color.rgb(1.0, 1.0, 1.0)],
 *   "custom",
 *   "twotone, black and white"
 * );
 * ```
 */
export class ColorScheme {
  public readonly colors: Color[];
  public readonly category: string;
  public readonly notes: string;

  constructor(
    colors: ColorLike[],
    category: string = '',
    notes: string = ''
  ) {
    this.colors = colors.map((c) => Color.from(c));
    this.category = category;
    this.notes = notes;
  }

  get length(): number {
    return this.colors.length;
  }

  /**
   * Iterable protocol support (for...of loops).
   */
  [Symbol.iterator](): Iterator<Color> {
    return this.colors[Symbol.iterator]();
  }

  /**
   * Index access matching array lookup (0-based).
   */
  at(index: number): Color | undefined {
    if (index < 0) {
      index = this.colors.length + index;
    }
    return this.colors[index];
  }

  /**
   * `get(cscheme, inData, rangeScale = 'clamp')`
   * `get(cscheme, inData, rangeScale = [minVal, maxVal])`
   *
   * Return a Color generated by applying the colorscheme to the input data value.
   *
   * If `rangeScale` is `'clamp'`, the colorscheme is applied to values between 0.0-1.0,
   * and values outside this range get clamped to the ends of the colorscheme.
   *
   * If `rangeScale` is `'extrema'`, the colorscheme is applied to the range
   * `minimum(inData)..maximum(inData)`.
   *
   * Else, if `rangeScale` is `'centered'`, the colorscheme is applied to the range
   * `-maximum(abs, inData)..maximum(abs, inData)`.
   */
  get(x: boolean): Color;
  get(x: number, rangeScale?: RangeScale): Color;
  get(x: number | boolean, rangeScale?: RangeScale): Color {
    if (typeof x === 'boolean') {
      return x ? this.colors[this.colors.length - 1] : this.colors[0];
    }

    const range = computeRange([x], rangeScale);
    return this.getVal(x, range);
  }

  private getVal(x: number, range: [number, number]): Color {
    const n = this.colors.length;
    if (n === 0) {
      return new Color(0, 0, 0, 1);
    }
    if (n === 1) {
      return this.colors[0];
    }

    let [rangemin, rangemax] = range;
    if (rangemax === rangemin) {
      rangemin = 0;
      rangemax = 1;
    }

    const scaleby = (n - 1) / (rangemax - rangemin);
    const xclamp = Math.min(rangemax, Math.max(rangemin, x));
    const pos = (xclamp - rangemin) * scaleby;
    const before = Math.floor(pos);
    const after = Math.min(before + 1, n - 1);
    const cpt = pos - before;

    // Blend between the two colors adjacent to the point
    return Color.weightedColorMean(1 - cpt, this.colors[before], this.colors[after]);
  }

  /**
   * Return an array of colors generated by applying the colorscheme to 1D or 2D input data.
   */
  getArray(data: number[], rangeScale?: RangeScale): Color[];
  getArray(data: number[][], rangeScale?: RangeScale): Color[][];
  getArray(data: number[] | number[][], rangeScale?: RangeScale): Color[] | Color[][] {
    if (data.length === 0) return [];

    if (Array.isArray(data[0])) {
      const grid = data as number[][];
      const flat = grid.flat();
      const range = computeRange(flat, rangeScale);
      return grid.map((row) => row.map((val) => this.getVal(val, range)));
    }

    const flat = data as number[];
    const range = computeRange(flat, rangeScale);
    return flat.map((val) => this.getVal(val, range));
  }

  /**
   * `getinverse(cscheme, c, rangeScale = [0.0, 1.0])`
   *
   * Computes where the provided Color `c` would fit in `cscheme`.
   *
   * This is the inverse of `get()` — it returns the value `x` in the provided `rangeScale`
   * for which `get(scheme, x)` would most closely match the provided Color `c`.
   *
   * ### Example
   * ```typescript
   * getinverse(colorschemes['leonardo'], Color.rgb(1, 0, 0));
   * // 0.624899...
   * ```
   */
  getInverse(
    colorInput: ColorLike,
    rangeScale: [number, number] = [0, 1]
  ): number {
    const n = this.colors.length;
    if (n <= 1) {
      throw new Error(`ColorScheme length (${n}) is not long enough for getInverse`);
    }

    const target = Color.from(colorInput);
    const cdiffs = this.colors.map((c) => Color.colorDiff(target, c));

    let closest = 0;
    let minDiff = cdiffs[0];
    for (let i = 1; i < n; i++) {
      if (cdiffs[i] < minDiff) {
        minDiff = cdiffs[i];
        closest = i;
      }
    }

    let left = 0;
    let right = 0;
    if (closest === 0) {
      left = 0;
      right = 1;
    } else if (closest === n - 1) {
      left = n - 2;
      right = n - 1;
    } else {
      const nextClosest =
        cdiffs[closest - 1] < cdiffs[closest + 1] ? closest - 1 : closest + 1;
      left = Math.min(closest, nextClosest);
      right = Math.max(closest, nextClosest);
    }

    let v = left;
    if (cdiffs[left] !== cdiffs[right]) {
      v += cdiffs[left] / (cdiffs[left] + cdiffs[right]);
    }

    return remap(v, 0, n - 1, rangeScale[0], rangeScale[1]);
  }

  /**
   * `reverse(cscheme)`
   *
   * Make a new ColorScheme with the same colors as `cscheme` but in reverse order.
   */
  reverse(): ColorScheme {
    return new ColorScheme(
      [...this.colors].reverse(),
      this.category,
      this.notes
    );
  }

  /**
   * `concat(cscheme1, cscheme2)`
   *
   * Create new colorscheme by concatenating two colorschemes.
   */
  concat(other: ColorScheme): ColorScheme {
    return new ColorScheme(
      [...this.colors, ...other.colors],
      this.category || other.category,
      `${this.notes} concatenated with ${other.notes}`.trim()
    );
  }

  /**
   * `resample(cs, n = 10, alphaFunction?)`
   *
   * Create a new colorscheme that samples an existing colorscheme `cs` `n` times.
   * Optionally applies `alphaFunction(t)` at each sampling point to set the alpha opacity value.
   *
   * ### Example
   * ```typescript
   * // set all 20 colors in scheme to alpha 0.5
   * resample(colorschemes['turbo'], 20, (a) => 0.5);
   * ```
   */
  resample(n: number = 10, alphaFn?: (t: number) => number): ColorScheme {
    const count = Math.max(n, 2);
    const newColors: Color[] = [];

    for (let i = 0; i < count; i++) {
      const t = i / (count - 1);
      let col = this.get(t);
      if (alphaFn) {
        col = col.withAlpha(alphaFn(t));
      }
      newColors.push(col);
    }

    const notesSuffix = alphaFn ? ` resampled ${count} with alpha` : ` resampled ${count}`;
    return new ColorScheme(newColors, this.category, this.notes + notesSuffix);
  }
}

/**
 * `get(cscheme, inData, rangeScale = 'clamp')`
 *
 * Return a single Color or array of Colors by applying the colorscheme to `inData`.
 */
export function get(cs: ColorScheme, x: boolean): Color;
export function get(cs: ColorScheme, x: number, rangeScale?: RangeScale): Color;
export function get(cs: ColorScheme, x: number[] | number[][], rangeScale?: RangeScale): Color[] | Color[][];
export function get(cs: ColorScheme, x: number | boolean | number[] | number[][], rangeScale?: RangeScale): Color | Color[] | Color[][] {
  if (typeof x === 'number' || typeof x === 'boolean') {
    return cs.get(x as any, rangeScale);
  }
  return cs.getArray(x as any, rangeScale);
}

/**
 * `getinverse(cscheme, color, rangeScale = [0.0, 1.0])`
 *
 * Computes where the provided Color `c` would fit in `cscheme`.
 */
export function getInverse(cs: ColorScheme, color: ColorLike, rangeScale?: [number, number]): number {
  return cs.getInverse(color, rangeScale);
}

export const getinverse = getInverse;

/**
 * `resample(cscheme, n = 10, alphaFunction?)`
 *
 * Create a new colorscheme that samples an existing colorscheme `n` times.
 */
export function resample(cs: ColorScheme, n?: number, alphaFn?: (t: number) => number): ColorScheme {
  return cs.resample(n, alphaFn);
}

// Oxford Spelling Aliases matching ColorSchemes.jl
export const ColourScheme = ColorScheme;
export const ColourSchemeCategory = ColorSchemeCategory;
